#!/bin/sh -e
#
# Get IP address

docker_instance=$(docker-machine ls | grep coderdojochi-dev)
if [[ "$docker_instance" == *"Stopped"* ]]; then
    docker-machine start coderdojochi-dev
elif [[ "$docker_instance" == *"Running"* ]]; then
    eval "$(docker-machine env coderdojochi-dev)"
fi

docker-machine ip coderdojochi-dev
