#!/bin/bash -e
#
# Load fixtures

docker_instance=$(docker-machine ls | grep coderdojochi-dev)
if [[ "$docker_instance" == *"Stopped"* ]]; then
    docker-machine start coderdojochi-dev
elif [[ "$docker_instance" == *"Saved"* ]]; then
    docker-machine start coderdojochi-dev
elif [[ "$docker_instance" == *"Running"* ]]; then
    eval "$(docker-machine env coderdojochi-dev)"
fi

docker-compose -f ./resources/docker/docker-compose.yml run app python manage.py loaddata \
    /fixtures/coderdojochi.json \
    /fixtures/sites.json \
    /fixtures/socialaccount.json
