#!/bin/bash -e
#
# Create new migration scripts (dropped into your repo via magic of shared folders)

docker_instance=$(docker-machine ls | grep coderdojochi-dev)
if [[ "$docker_instance" == *"Stopped"* ]]; then
    docker-machine start coderdojochi-dev
elif [[ "$docker_instance" == *"Saved"* ]]; then
    docker-machine start coderdojochi-dev
elif [[ "$docker_instance" == *"Running"* ]]; then
    eval "$(docker-machine env coderdojochi-dev)"
fi

docker exec -it docker_app_1 python manage.py $@
