#!/bin/bash -e
#
# Load up bash

$(dirname $0)/init
$(dirname $0)/build
$(dirname $0)/setup-manage migrate
$(dirname $0)/setup-manage loaddata \
    /fixtures/coderdojochi.json \
    /fixtures/sites.json \
    /fixtures/socialaccount.json
$(dirname $0)/ip
$(dirname $0)/serve
