# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import django.utils.timezone
from django.conf import settings
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDCUser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', unique=True, max_length=30, verbose_name='username', validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username.', 'invalid')])),
                ('first_name', models.CharField(max_length=30, verbose_name='first name', blank=True)),
                ('last_name', models.CharField(max_length=30, verbose_name='last name', blank=True)),
                ('email', models.EmailField(max_length=75, verbose_name='email address', blank=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, max_length=10, null=True, choices=[(b'mentor', b'mentor'), (b'guardian', b'guardian')])),
                ('admin_notes', models.TextField(null=True, blank=True)),
                ('groups', models.ManyToManyField(related_query_name='user', related_name='user_set', to='auth.Group', blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of his/her group.', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(related_query_name='user', related_name='user_set', to='auth.Permission', blank=True, help_text='Specific permissions for this user.', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=255, null=True, blank=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40, null=True, blank=True)),
                ('description', models.TextField(help_text=b'Basic HTML allowed', null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=75)),
                ('amount', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nickname', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text=b'Basic HTML allowed', null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'email content',
                'verbose_name_plural': 'email content',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('asset_tag', models.CharField(max_length=255)),
                ('aquisition_date', models.DateTimeField()),
                ('condition', models.CharField(max_length=255, choices=[(b'working', b'Working'), (b'issue', b'Issue'), (b'unusable', b'Unusable')])),
                ('notes', models.TextField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'equiptment',
                'verbose_name_plural': 'equiptment',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('first_name', models.CharField(max_length=255, null=True, blank=True)),
                ('last_name', models.CharField(max_length=255, null=True, blank=True)),
                ('active', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=50, blank=True)),
                ('zip', models.CharField(max_length=20, null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'guardian',
                'verbose_name_plural': 'guardians',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255, null=True, verbose_name=b'Address 2', blank=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=20)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('additional_info', models.TextField(help_text=b'Basic HTML allowed', null=True, blank=True)),
                ('start_date', models.DateTimeField(null=True, blank=True)),
                ('end_date', models.DateTimeField(null=True, blank=True)),
                ('external_enrollment_url', models.CharField(help_text=b'When provided, local enrollment is disabled.', max_length=255, null=True, blank=True)),
                ('public', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('image_url', models.CharField(max_length=255, null=True, blank=True)),
                ('bg_image', models.ImageField(null=True, upload_to=b'', blank=True)),
                ('announced_date', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(to='coderdojochi.Location')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=255, null=True, blank=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40, null=True, blank=True)),
                ('description', models.TextField(help_text=b'Basic HTML allowed', null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'meeting type',
                'verbose_name_plural': 'meeting types',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('first_name', models.CharField(max_length=255, null=True, blank=True)),
                ('last_name', models.CharField(max_length=255, null=True, blank=True)),
                ('bio', models.TextField(null=True, blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_attended_intro_meeting', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mentors',
                'verbose_name_plural': 'mentors',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('active', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=255, null=True, blank=True)),
                ('check_in', models.DateTimeField(null=True, blank=True)),
                ('alternate_guardian', models.CharField(max_length=255, null=True, blank=True)),
                ('affiliate', models.CharField(max_length=255, null=True, blank=True)),
                ('order_number', models.CharField(max_length=255, null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_reminder_sent', models.BooleanField(default=False)),
                ('day_reminder_sent', models.BooleanField(default=False)),
                ('guardian', models.ForeignKey(to='coderdojochi.Guardian')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2016, 1, 10, 10, 0))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2016, 1, 10, 13, 0))),
                ('mentor_start_date', models.DateTimeField(default=datetime.datetime(2016, 1, 10, 9, 0))),
                ('mentor_end_date', models.DateTimeField(default=datetime.datetime(2016, 1, 10, 14, 0))),
                ('capacity', models.IntegerField(default=20)),
                ('mentor_capacity', models.IntegerField(null=True, blank=True)),
                ('additional_info', models.TextField(help_text=b'Basic HTML allowed', null=True, blank=True)),
                ('external_enrollment_url', models.CharField(help_text=b'When provided, local enrollment is disabled.', max_length=255, null=True, blank=True)),
                ('active', models.BooleanField(default=False, help_text=b'Session is active.')),
                ('public', models.BooleanField(default=False, help_text=b'Session is a public session.')),
                ('announced_date', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=255, null=True, blank=True)),
                ('bg_image', models.ImageField(null=True, upload_to=b'', blank=True)),
                ('mentors_week_reminder_sent', models.BooleanField(default=False)),
                ('mentors_day_reminder_sent', models.BooleanField(default=False)),
                ('course', models.ForeignKey(to='coderdojochi.Course')),
                ('location', models.ForeignKey(to='coderdojochi.Location')),
                ('mentors', models.ManyToManyField(related_name='session_mentors', null=True, to='coderdojochi.Mentor', blank=True)),
                ('teacher', models.ForeignKey(related_name='session_teacher', to='coderdojochi.Mentor')),
                ('waitlist_mentors', models.ManyToManyField(related_name='session_waitlist_mentors', null=True, to='coderdojochi.Mentor', blank=True)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField()),
                ('gender', models.CharField(max_length=255)),
                ('medical_conditions', models.TextField(null=True, blank=True)),
                ('medications', models.TextField(null=True, blank=True)),
                ('photo_release', models.BooleanField(default=False, help_text=b"I hereby give permission to CoderDojoChi to use the student's image and/or likeness in promotional materials.", verbose_name=b'Photo Consent')),
                ('consent', models.BooleanField(default=False, help_text=b'I hereby give consent for the student signed up above to participate in CoderDojoChi.', verbose_name=b'General Consent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('guardian', models.ForeignKey(to='coderdojochi.Guardian')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='session',
            name='waitlist_students',
            field=models.ManyToManyField(related_name='session_waitlist_students', null=True, to='coderdojochi.Student', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.ForeignKey(to='coderdojochi.Session'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='order',
            name='student',
            field=models.ForeignKey(to='coderdojochi.Student'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.ForeignKey(to='coderdojochi.MeetingType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='meeting',
            name='mentors',
            field=models.ManyToManyField(related_name='meeting_mentors', null=True, to='coderdojochi.Mentor', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(to='coderdojochi.EquipmentType'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(to='coderdojochi.Location'),
            preserve_default=True,
        ),
    ]
