# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 15:06
from __future__ import unicode_literals

import coderdojochi.models
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cdcuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='has_attended_intro_meeting',
            new_name='background_check',
        ),
        migrations.AddField(
            model_name='mentor',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, upload_to=coderdojochi.models.generate_filename),
        ),
        migrations.AddField(
            model_name='mentor',
            name='avatar_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cdcuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='cdcuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='cdcuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='cdcuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='meeting_mentors', to='coderdojochi.Mentor'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentor_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentor_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='session_mentors', to='coderdojochi.Mentor'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='waitlist_mentors',
            field=models.ManyToManyField(blank=True, related_name='session_waitlist_mentors', to='coderdojochi.Mentor'),
        ),
        migrations.AlterField(
            model_name='session',
            name='waitlist_students',
            field=models.ManyToManyField(blank=True, related_name='session_waitlist_students', to='coderdojochi.Student'),
        ),
    ]
