# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0002_auto_20160109_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentor_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentor_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
