# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 19:24
from __future__ import unicode_literals

from django.db import migrations

def move_first_and_last_names_to_user_model(apps, schema_editor):
    Mentor = apps.get_model('coderdojochi', 'Mentor')
    Guardian = apps.get_model('coderdojochi', 'Guardian')
    User = apps.get_model('coderdojochi', 'CDCUser')

    for mentor in Mentor.objects.all():
        this_user = User.objects.get(id=mentor.user.id)
        this_user.first_name = mentor.user.first_name
        this_user.last_name = mentor.user.last_name
        this_user.save()

    for guardian in Guardian.objects.all():
        this_user = User.objects.get(id=guardian.user.id)
        this_user.first_name = guardian.user.first_name
        this_user.last_name = guardian.user.last_name
        this_user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0002_auto_20160518_0028'),
    ]

    operations = [
        migrations.RunPython(move_first_and_last_names_to_user_model),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'equipment', 'verbose_name_plural': 'equipment'},
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='last_name',
        ),
    ]
