# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0004_auto_20160426_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='has_attended_intro_meeting',
            new_name='avatar_approved',
        ),
        migrations.AddField(
            model_name='mentor',
            name='background_check',
            field=models.BooleanField(default=False),
        ),
    ]
