# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0004_auto_20160718_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentororder',
            name='waitlist_offer_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentororder',
            name='waitlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentororder',
            name='waitlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waitlist_offer_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waitlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='waitlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='force_update_on_next_boot',
            field=models.BooleanField(default=False, verbose_name=b'Force Update'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_system_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Last Update'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_system_update_check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Last Check In'),
        ),
    ]
