# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 14:58
from __future__ import unicode_literals

import coderdojochi.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0005_auto_20160426_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, upload_to=coderdojochi.models.generate_filename),
        ),
    ]
