# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 18:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0006_session_gender_limitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_age_limitation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='session',
            name='min_age_limitation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
