# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0007_waitlist_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='gender_limitation',
            field=models.CharField(blank=True, choices=[(b'male', b'Male'), (b'female', b'Female')], max_length=255, null=True),
        ),
    ]
