# Generated by Django 1.9.6 on 2016-09-20 17:56


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0007_partner_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPasswordAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coderdojochi.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_password_access',
                'verbose_name': 'partner_password_access',
            },
        ),
    ]
