# Generated by Django 1.9.6 on 2016-09-24 14:19


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0008_partnerpasswordaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_age_limitation',
            field=models.IntegerField(default=17, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='session',
            name='min_age_limitation',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
