# Generated by Django 1.10.5 on 2017-01-27 04:22


import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0010_donation_session_and_user_relations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcontent',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='meetingorder',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='mentororder',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='active',
            new_name='is_active',
        ),
    ]
