# Generated by Django 1.10.5 on 2017-01-27 04:33


import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0011_active_to_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='public',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='public',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='public',
            new_name='is_public',
        ),
    ]
