# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 04:36
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0012_public_to_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raceethnicity',
            old_name='visible',
            new_name='is_visible',
        ),
    ]
