# Generated by Django 1.10.5 on 2017-01-28 00:23


import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0013_visible_to_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
