# Generated by Django 2.0.6 on 2018-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0017_auto_20180605_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdcuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
