# Generated by Django 2.0.6 on 2018-08-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0018_auto_20180606_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='race_ethnicity',
            field=models.ManyToManyField(blank=True, to='coderdojochi.RaceEthnicity'),
        ),
    ]
