# Generated by Django 2.0.6 on 2018-08-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0019_auto_20180815_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='shirt_size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], max_length=5, null=True),
        ),
    ]
