# Generated by Django 2.1 on 2018-10-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0021_auto_20180815_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='shirt_size',
        ),
    ]
