# Generated by Django 2.1.5 on 2019-01-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0022_remove_mentor_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address2',
        ),
    ]
