# Generated by Django 2.2.4 on 2019-08-22 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0025_course_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='teacher',
            new_name='instructor',
        ),
    ]
