# Generated by Django 2.2.6 on 2019-10-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0026_teacher_to_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'user__groups__name': 'Instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_instructor', to='coderdojochi.Mentor'),
        ),
    ]
