# Generated by Django 2.2.6 on 2019-10-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0027_instructor_limit_choiced_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceethnicity',
            options={'verbose_name': 'Race/Ethnicity', 'verbose_name_plural': 'Race/Ethnicities'},
        ),
    ]
