# Generated by Django 2.2.9 on 2020-01-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0029_course_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='end_date',
            new_name='old_end_date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='mentor_end_date',
            new_name='old_mentor_end_date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='mentor_start_date',
            new_name='old_mentor_start_date',
        ),
    ]
