# Generated by Django 3.0.4 on 2020-03-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0029_course_duration_squashed_0040_auto_20200102_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('WE', 'Weekend'), ('CA', 'Camp'), ('SP', 'Special')], default='WE', max_length=2, verbose_name='type'),
        ),
    ]
