# Generated by Django 3.0.7 on 2020-06-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0031_auto_20200529_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='online_video_description',
            field=models.TextField(blank=True, null=True, verbose_name='Online Video Description'),
        ),
        migrations.AddField(
            model_name='session',
            name='online_video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Online Video Link'),
        ),
    ]
