# Generated by Django 3.0.7 on 2020-07-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0032_auto_20200615_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='online_video_meeting_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Online Video Meeting ID'),
        ),
        migrations.AddField(
            model_name='session',
            name='online_video_meeting_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Online Video Meeting Password'),
        ),
        migrations.AlterField(
            model_name='session',
            name='online_video_description',
            field=models.TextField(blank=True, help_text='Information on how to connect to the video call. Basic HTML allowed.', null=True, verbose_name='Online Video Description'),
        ),
        migrations.AlterField(
            model_name='session',
            name='online_video_link',
            field=models.URLField(blank=True, help_text='Zoom link with password.', null=True, verbose_name='Online Video Link'),
        ),
    ]
