# Generated by Django 3.0.7 on 2020-08-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0033_auto_20200714_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='online_video_meeting_id',
            field=models.CharField(blank=True, help_text='XXX XXXX XXXX', max_length=255, null=True, verbose_name='Online Video Meeting ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='online_video_meeting_password',
            field=models.CharField(blank=True, help_text='Plain text password shared by Zoom', max_length=255, null=True, verbose_name='Online Video Meeting Password'),
        ),
    ]
