# Generated by Django 3.0.7 on 2020-08-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0035_auto_20200811_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meetingorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meetingtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mentororder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partnerpasswordaccess',
            options={},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
