# Generated by Django 2.2.9 on 2020-01-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0035_auto_20200101_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
