# Generated by Django 3.1.2 on 2020-12-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0036_auto_20200812_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdcuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
