# Generated by Django 3.1.5 on 2021-01-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0036_auto_20210115_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meetingorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meetingtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mentororder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partnerpasswordaccess',
            options={},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
