# Generated by Django 3.1.5 on 2021-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0037_auto_20210118_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='coderdojochi.Course'),
        ),
    ]
