# Generated by Django 3.1.6 on 2021-06-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0038_auto_20210221_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='mentor_capacity',
            field=models.IntegerField(default=10),
        ),
    ]
