# Generated by Django 2.2.9 on 2020-01-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0038_auto_20200102_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='max_cost',
            new_name='maximum_cost',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='min_cost',
            new_name='minimum_cost',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='override_max_age_limitation',
            new_name='override_maximum_age_limitation',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='override_min_age_limitation',
            new_name='override_minimum_age_limitation',
        ),
    ]
