# Generated by Django 2.2.9 on 2020-01-03 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0039_auto_20200102_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='gender_limitation',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Limits the class to be only one gender.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='override_maximum_age_limitation',
            field=models.IntegerField(blank=True, help_text='Only update this if different from the default.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max Age'),
        ),
        migrations.AlterField(
            model_name='session',
            name='override_minimum_age_limitation',
            field=models.IntegerField(blank=True, help_text='Only update this if different from the default.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Min Age'),
        ),
    ]
