# Generated by Django 3.2.5 on 2021-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0040_auto_20210722_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='student',
            name='race',
        ),
        migrations.AddField(
            model_name='student',
            name='race_ethnicity',
            field=models.ManyToManyField(blank=True, to='coderdojochi.RaceEthnicity'),
        ),
    ]
