# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0040_alter_mentor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation or no-show', null=True),
        ),
    ]