# Generated by Django 3.2.5 on 2021-07-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0042_auto_20210727_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
