# Generated by Django 3.0.4 on 2020-03-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Chair', 'Chair'), ('Vice Chair', 'Vice Chair'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Director', 'Director')], default='Director', max_length=255)),
                ('description', models.CharField(max_length=255,blank=True, null=True,)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='board/')),
            ],
            options={
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board Members',
            },
        ),
    ]
