# Generated by Django 3.0.6 on 2020-05-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weallcode', '0004_auto_20200518_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
