# Generated by Django 3.0.7 on 2020-06-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weallcode', '0005_auto_20200518_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associateboardmember',
            name='role',
            field=models.CharField(choices=[('Chair', 'Chair'), ('Vice Chair', 'Vice Chair'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Director', 'Director'), ('President', 'President')], default='Director', max_length=255),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.CharField(choices=[('Chair', 'Chair'), ('Vice Chair', 'Vice Chair'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Director', 'Director'), ('President', 'President')], default='Director', max_length=255),
        ),
    ]
