# Generated by Django 3.1.2 on 2020-12-29 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weallcode', '0006_auto_20200615_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associateboardmember',
            options={},
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staffmember',
            options={},
        ),
        migrations.AddField(
            model_name='associateboardmember',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Join Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardmember',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Join Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Join Date'),
            preserve_default=False,
        ),
    ]
