# Generated by Django 3.1.6 on 2021-03-23 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weallcode', '0007_auto_20201229_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateboardmember',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Departure Date'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Departure Date'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='associateboardmember',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Join Date'),
        ),
    ]
